### PR TITLE
Kevin's answers

### PR DESCRIPTION
**Pull request by kaveWalker**
- created a txt file that contains my answers
- created unit-test.html and unit-test.js to run a simple unit test
written with QUnit

### CODE REVIEW

**Comment by grabcode** [comment]
Thanks Kevin. Almost perfect but there's a few things that would need more clarity. Regarding the =>, and the technique of storing `this` (ex: `var _this = this`), it wouldn't always work and I reckon it is best often clearer to use `myFunction.call()` or `myFunction.apply()`.

**Comment by kevin-bao** [comment]
@grabcode  Thank you so much for your time and comment. The way how you solve the context issue within a function is so neat and clean. Thanks a lot for teaching me this. I really appreciate it.

**Comment by grabcode** [comment]
No worries Kevin. I strongly recommend to follow this [email course](http://derickbailey.com/email-courses/masteringthis/] from Derick Bailey. Also, you might want to check out [Egghead.io](https://egghead.io/), a great source of high quality tutorials.

**Comment by kaveWalker** [comment]
Jesus, Egghead.io has almost everything I want, such as AngularJs, Angular2, Node and React.
Thank you again for the source.

As you mentioned in your first comment, there are a few things need to be clearer.
Would you mind to let me know what they are, apart from the context one? (keen on learning)

Cheers

**Pull request closed without merging**
